# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Email',
            field=models.EmailField(default=12, max_length=254),
            preserve_default=False,
        ),
    ]
